#! /bin/sh

killall -q picom
picom  --experimental-backend &
nm-applet &
pgrep -x sxhkd > /dev/null || sxhkd &
wmname LG3D &
feh --bg-scale /home/camilo/Wallpapers/bg_13.jpg &
~/.config/polybar/launch.sh --transparent &
killall mate-notification-daemon
dunst &

bspc config pointer_modifier mod1
bspc config focus_follows_pointer true

bspc monitor -d 1 2 3 4 5
bspc config border_width         1
bspc config window_gap           5

bspc config border_radius 	     false
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true

# Other floating windows
bspc rule --add feh                         state=floating
bspc rule --add mplayer2                    state=floating
bspc rule --add mpv                         state=floating
bspc rule --add Nautilus                    state=floating

# Colors
bspc config normal_border_color "#00000000"
bspc config active_border_color "#0000000"
bspc config focused_border_color "#ffffff07"

# Autostatr apps
